### ISSUE TITLE
Mastodon Cannot Send Any Activity in 3.4.4~ynh2

### ISSUE THREAD

**Issue by myprivacyisgone** [YunoHost-Apps/mastodon_ynh#296]
### Mastodon Cannot Send Any Activity
All was working well until I upgraded Yunohost from 4.3.6 to 4.3.6.2, Mastodon from `3.4.4~ynh1` to `3.4.4~ynh2`. All function works however my instance do not deliver any activity to remote instances.

### Context

- Hardware: VPS with Debian 10
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH and through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Steps to reproduce

Send Toot/Favourite Toot >> No activity is being Sent to other instance through ActivityPub

### Expected behavior

Send Toot/Favourite  >>  Activities is being Sent to other instance through ActivityPub

### Logs

- mastodon-sidekiq:
https://paste.yunohost.org/yusatocipa.tex

- mastodon-streaming:
https://paste.yunohost.org/egivilaxuv

**Comment by yalh76** [comment]
changes between 3.4.4~ynh1 and 3.4.4~ynh2 is just https://github.com/YunoHost-Apps/mastodon_ynh/pull/294, around sso

**Comment by Tagadda** [comment]
I did a quick test, applying the sso patch to `3.4.4~ynh1` and could not reproduce.
Aaaand there's #292 too :P So I did investigate a bit and after some more tests, I think this come from the systemd sandboxing stuff.

**Comment by Tagadda** [comment]
Thanks for the report @myprivacyisgone ! This should be fixed in the last revision.
You can force the upgrade and it should fix your instance
`sudo yunohost app upgrade mastodon --force`

**Comment by myprivacyisgone** [comment]
@Tagadda @yalh76 
Thank you for looking into this. However, the issue still occurs with identical logs above. 
I have tried debugging my instance according to https://github.com/mastodon/mastodon/issues/6916, but there is no luck. 
I will try setting nginx/ssl configs and other stuffs to fix my instance.

**Comment by myprivacyisgone** [comment]
@yalh76 @Tagadda 

I suspect the issue actually caused by the 3.4.4~ynh2 upgrade. I fixed my instance by reverting it to `3.4.4~ynh1`, aka this [branch](https://github.com/YunoHost-Apps/mastodon_ynh/tree/fa8a9d4eed460fa73926e7874313091dffb7b9fc).


My steps to reproduce the fix:
- pg_dump the database to somewhere safe
`sudo -u mastodon  pg_dump -Fc mastodon_production -f backup.dump`
- Remove mastodon with `yunohost app remove mastodon`
- Remove the domain that mastodon installed with `yunohost domain remove domaine.net`
- Re-create the domain, `yunohost domain add domaine.net`
- Install cert, `yunohost domain cert-install xgix.net --no-checks`
- Install version `3.4.4~ynh1`, with `yunohost app install https://github.com/YunoHost-Apps/mastodon_ynh/tree/fa8a9d4eed460fa73926e7874313091dffb7b9fc`
- Remove mastodon database
- Recreate database, `sudo -u mastodon createdb -T template0 mastodon_production`
- Restore dump, `pg_restore -Fc -U mastodon -n public --no-owner --role=mastodon   -d mastodon_production backup.dump`

Here are the logs after re-installation:
- mastodon-sidekiq: https://paste.yunohost.org/dadanecaji
- https://paste.yunohost.org/bepebeyaso

For further debugging, I am going to do some federation tests with a fresh-installed 3.4.4~ynh2.

**Comment by myprivacyisgone** [comment]
By the way, I actually did a backup-remove-restore procedure with nginx and mastodon_ynh 3.4.4~ynh2 and it turns out nothing.

**Comment by Tagadda** [comment]
The `HTTP::ConnectionError: failed to connect: Address family not supported by protocol - getifaddrs on ...` should be fixed with [this branch](https://github.com/YunoHost-Apps/mastodon_ynh/tree/df52f82e19c7f24a4dad26cb03b36f94201186a9)

**Comment by myprivacyisgone** [comment]
@Tagadda 
Sorry for misreading your message. The fix worked like a charm, thank you.
